<?php
    $servidor = $_GET['server'];
    $user = $_GET['user'];
    $pass = $_GET['pass'];
    $db = $_GET['db'];
    $url = $_GET['url'];

$conn = '<?php 
    $local= "' . $servidor .'";
    $usuario= "' . $user . '";
    $contra= "' . $pass . '";
    $dataBase= "' . $db . '";
    $urlPartner= "' . $url . '";
    
?>';

$access = 'RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^([^\.]+)$ $1.php [NC,L]
RewriteRule ^([^\.]+)$ $1.html [NC,L]

RewriteEngine On
RewriteCond %{SERVER_PORT} 80
RewriteRule ^(.*)$ ' . $url . '$1 [R,L]

ErrorDocument 404 ' . $url . '404.php
ErrorDocument 500 ' . $url . '404.php';

// $access ='<FilesMatch "\.(html|htm|js|css|php)$">
// FileETag None
// <IfModule mod_headers.c>
//     Header unset ETag
//     Header set Cache-Control "max-age=0, no-cache, no-store, must-revalidate"
//     Header set Pragma "no-cache"
//     Header set Expires "Wed, 11 Jan 1984 05:00:00 GMT"
// </IfModule>
// </FilesMatch>

// RewriteEngine On
// RewriteCond %{REQUEST_FILENAME} !-f
// RewriteRule ^([^\.]+)$ $1.php [NC,L]
// RewriteRule ^([^\.]+)$ $1.html [NC,L]

// RewriteEngine On
// RewriteCond %{SERVER_PORT} 80
// RewriteRule ^(.*)$ ' . $url . '/$1 [R,L]

// ErrorDocument 404 ' . $url . '404
// ErrorDocument 500 ' . $url . '404

// # php -- BEGIN cPanel-generated handler, do not edit
// # Set the “ea-php82” package as the default “PHP” programming language.
// <IfModule mime_module>
// AddHandler application/x-httpd-ea-php82___lsphp .php .php8 .phtml
// </IfModule>
// # php -- END cPanel-generated handler, do not edit
// ';

        $connBoletyos = '<?php
    include "app/vConn.php";
    class ApptivaDB{   


        private $host = "' . $servidor . '";
        private $usuario = "' . $user . '";
        private $clave = "' . $pass . '";
        private $db = "' . $db . '";
        public $conexion;

        public function __construct(){
            $this->conexion = new mysqli($this->host, $this->usuario, $this->clave,$this->db)
            or die(mysql_error());
            $this->conexion->set_charset("utf8");
        }

        public function buscar($tabla, $condicion){
            $resultado = $this->conexion->query("SELECT * FROM $tabla WHERE $condicion") or die($this->conexion->error);
            if($resultado)
                return $resultado->fetch_all(MYSQLI_ASSOC);
            return false;
        } 
    }

?>';


        $robots = '# robots.txt generated by smallseotools.com
User-agent: Googlebot
Disallow: 
User-agent: googlebot-image
Disallow: 
User-agent: googlebot-mobile
Disallow: 
User-agent: MSNBot
Disallow: 
User-agent: Slurp
Disallow: 
User-agent: Teoma
Disallow: 
User-agent: Gigabot
Disallow: 
User-agent: Robozilla
Disallow: 
User-agent: Nutch
Disallow: 
User-agent: ia_archiver
Disallow: 
User-agent: baiduspider
Disallow: 
User-agent: naverbot
Disallow: 
User-agent: yeti
Disallow: 
User-agent: yahoo-mmcrawler
Disallow: 
User-agent: psbot
Disallow: 
User-agent: yahoo-blogs/v3.9
Disallow: 
User-agent: *
Disallow: 
Disallow: /cgi-bin/
Sitemap: ' . $url ;

        $archivovConn = fopen('../app/vConn.php','w');
        fputs($archivovConn, $conn);
        fclose($archivovConn);

        // access raiz
        $archivoAccessRaiz = fopen('../.htaccess','w');
        fputs($archivoAccessRaiz, $access);
        fclose($archivoAccessRaiz);

        // access panel
        $archivoAccessPanel = fopen('../user_v2/.htaccess','w');
        fputs($archivoAccessPanel, $access);
        fclose($archivoAccessPanel);

        // access script
        $archivoAccessScript = fopen('.htaccess','w');
        fputs($archivoAccessScript, $access);
        fclose($archivoAccessScript);

        // concecion a Boletos
        $archivoBoletosConexcion = fopen('../app/vConnCheck.php','w');
        fputs($archivoBoletosConexcion, $connBoletyos);
        fclose($archivoBoletosConexcion);

        // Robots
        $archivoBoletosRobots = fopen('../robots.txt','w');
        fputs($archivoBoletosRobots, $robots);
        fclose($archivoBoletosRobots);
     
?>
    <a class="btn btn-primary shadow d-block w-100" style="background: crimson!important;border-color: crimson!important;" href="../">Ir a Inicio</a>